language: node_js
node_js:
  - "8"
before_script: npm install
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_API_KEY
  on:
    branch: master
  local_dir: dist
  repo: wh-Coder/wh-Coder.github.io
  target_branch: ci
  email: deploy@travis-ci.org
  name: deployment-bot
